### ISSUE TITLE
after upgrading monaco, vscode, service override packages to 5.2.0, `delegate.readFileStream is not a function`

### ISSUE THREAD

**Issue by alissa-tung** [CodinGame/monaco-vscode-api#435]
Hello, I had upgraded the monaco, vscode, service override packages to 5.2.0,

when calling `monaco.editor.createModelReference`, it throws `(TypeError: delegate.readFileStream is not a function)`

is there anything I can do to debug this issue? thank you

in my package.json

```
    "monaco-editor": "npm:@codingame/monaco-vscode-editor-api@^5.2.0",
    "vscode": "npm:@codingame/monaco-vscode-api@^5.2.0"
    "@codingame/monaco-vscode-files-service-override": "^5.2.0",
    "@codingame/monaco-vscode-model-service-override": "^5.2.0",
```

**Comment by CGNonofr** [comment]
I'm unable to reproduce nor understand how it can happen, do you have a stack trace?

**Comment by CGNonofr** [comment]
Are you using a custom filesystem provider? because delegate.readFileStream is only called if the delegate declares the FileReadStream capability

**Comment by alissa-tung** [comment]
> Are you using a custom filesystem provider? because delegate.readFileStream is only called if the delegate declares the FileReadStream capability

Yes, I am using a custom filesystem provider. Should I remove the `FileReadStream`  feature?

**Comment by CGNonofr** [comment]
A provider should only declare the FileReadStream capability if the readFileStream method is implemented, yes

**Comment by alissa-tung** [comment]
> A provider should only declare the FileReadStream capability if the readFileStream method is implemented, yes

got it, thank you
